//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppForm {
    
    
    public partial class CMD {
        
        /// <summary>
        /// txtcomplaintno control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtcomplaintno;
        
        /// <summary>
        /// btnSearch control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnSearch;
        
        /// <summary>
        /// lbl_crmsid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbl_crmsid;
        
        /// <summary>
        /// ref_lblCRMS_isd_stg control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ref_lblCRMS_isd_stg;
        
        /// <summary>
        /// lblCRMS_isd_stg control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCRMS_isd_stg;
        
        /// <summary>
        /// lblCRMS_isd_stgQR control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCRMS_isd_stgQR;
        
        /// <summary>
        /// lblCRMS_isd_stgQ control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCRMS_isd_stgQ;
        
        /// <summary>
        /// reflblCRMS_odw_stg control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label reflblCRMS_odw_stg;
        
        /// <summary>
        /// lblCRMS_odw_stg control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCRMS_odw_stg;
        
        /// <summary>
        /// lblCRMS_odw_stgQR control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCRMS_odw_stgQR;
        
        /// <summary>
        /// lblCRMS_odw_stgQ control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCRMS_odw_stgQ;
        
        /// <summary>
        /// reflblCRMS_odw_gis_tblhisty control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label reflblCRMS_odw_gis_tblhisty;
        
        /// <summary>
        /// lblCRMS_odw_gis_tblhisty control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCRMS_odw_gis_tblhisty;
        
        /// <summary>
        /// lblCRMS_odw_gis_tblhistyQR control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCRMS_odw_gis_tblhistyQR;
        
        /// <summary>
        /// lblCRMS_odw_gis_tblhistyQ control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCRMS_odw_gis_tblhistyQ;
        
        /// <summary>
        /// reflblCRMS_odw_gis_tbl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label reflblCRMS_odw_gis_tbl;
        
        /// <summary>
        /// lblCRMS_odw_gis_tbl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCRMS_odw_gis_tbl;
        
        /// <summary>
        /// lblCRMS_odw_gis_tblQR control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCRMS_odw_gis_tblQR;
        
        /// <summary>
        /// lblCRMS_odw_gis_tblQ control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCRMS_odw_gis_tblQ;
        
        /// <summary>
        /// reflblCRMS_odw_gis_vw control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label reflblCRMS_odw_gis_vw;
        
        /// <summary>
        /// lblCRMS_odw_gis_vw control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCRMS_odw_gis_vw;
        
        /// <summary>
        /// lblCRMS_odw_gis_vwQR control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCRMS_odw_gis_vwQR;
        
        /// <summary>
        /// lblCRMS_odw_gis_vwQ control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCRMS_odw_gis_vwQ;
        
        /// <summary>
        /// rreflblCRMS_odw_gis_srvce control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label rreflblCRMS_odw_gis_srvce;
        
        /// <summary>
        /// lblCRMS_odw_gis_srvce control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCRMS_odw_gis_srvce;
        
        /// <summary>
        /// lblCRMS_odw_gis_srvceQR control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCRMS_odw_gis_srvceQR;
        
        /// <summary>
        /// lblCRMS_odw_gis_srvceQ control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCRMS_odw_gis_srvceQ;
        
        /// <summary>
        /// reflblCRMS_odw_gis_rw control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label reflblCRMS_odw_gis_rw;
        
        /// <summary>
        /// lblCRMS_odw_gis_rw control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCRMS_odw_gis_rw;
        
        /// <summary>
        /// lblCRMS_odw_gis_rwQR control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCRMS_odw_gis_rwQR;
        
        /// <summary>
        /// lblCRMS_odw_gis_rwQ control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCRMS_odw_gis_rwQ;
        
        /// <summary>
        /// Label3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label3;
        
        /// <summary>
        /// lblCRMS_odw_gis_srvce_R control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCRMS_odw_gis_srvce_R;
        
        /// <summary>
        /// lblCRMS_odw_gis_srvce_RQR control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCRMS_odw_gis_srvce_RQR;
        
        /// <summary>
        /// lblCRMS_odw_gis_srvce_RQ control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCRMS_odw_gis_srvce_RQ;
        
        /// <summary>
        /// reflblCRMS_odw_gis_srvce control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label reflblCRMS_odw_gis_srvce;
        
        /// <summary>
        /// lblCRMS_odw_gis_noNrw control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCRMS_odw_gis_noNrw;
        
        /// <summary>
        /// lblCRMS_odw_gis_noNrwQR control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCRMS_odw_gis_noNrwQR;
        
        /// <summary>
        /// lblCRMS_odw_gis_noNrwQ control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCRMS_odw_gis_noNrwQ;
        
        /// <summary>
        /// Label1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label1;
        
        /// <summary>
        /// lblCRMS_odw_gis_srvce_nR control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCRMS_odw_gis_srvce_nR;
        
        /// <summary>
        /// lblCRMS_odw_gis_srvce_nRQR control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCRMS_odw_gis_srvce_nRQR;
        
        /// <summary>
        /// lblCRMS_odw_gis_srvce_nRQ control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCRMS_odw_gis_srvce_nRQ;
        
        /// <summary>
        /// lblEAMS_SR control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEAMS_SR;
        
        /// <summary>
        /// reflblEAMS_SR_isd_actdb control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label reflblEAMS_SR_isd_actdb;
        
        /// <summary>
        /// lblEAMS_SR_isd_actdb control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEAMS_SR_isd_actdb;
        
        /// <summary>
        /// lblEAMS_SR_isd_actdbQR control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEAMS_SR_isd_actdbQR;
        
        /// <summary>
        /// lblEAMS_SR_isd_actdbQ control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEAMS_SR_isd_actdbQ;
        
        /// <summary>
        /// reflblEAMS_SR_isd_stgdb control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label reflblEAMS_SR_isd_stgdb;
        
        /// <summary>
        /// lblEAMS_SR_isd_stgdb control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEAMS_SR_isd_stgdb;
        
        /// <summary>
        /// lblEAMS_SR_isd_stgdbQR control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEAMS_SR_isd_stgdbQR;
        
        /// <summary>
        /// lblEAMS_SR_isd_stgdbQ control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEAMS_SR_isd_stgdbQ;
        
        /// <summary>
        /// reflblEAMS_SR_isd_stgFC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label reflblEAMS_SR_isd_stgFC;
        
        /// <summary>
        /// lblEAMS_SR_isd_stgFC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEAMS_SR_isd_stgFC;
        
        /// <summary>
        /// lblEAMS_SR_isd_stgFCQR control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEAMS_SR_isd_stgFCQR;
        
        /// <summary>
        /// lblEAMS_SR_isd_stgFCQ control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEAMS_SR_isd_stgFCQ;
        
        /// <summary>
        /// reflblEAMS_SR_odw_stgdb control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label reflblEAMS_SR_odw_stgdb;
        
        /// <summary>
        /// lblEAMS_SR_odw_stgdb control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEAMS_SR_odw_stgdb;
        
        /// <summary>
        /// lblEAMS_SR_odw_stgdbQR control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEAMS_SR_odw_stgdbQR;
        
        /// <summary>
        /// lblEAMS_SR_odw_stgdbQ control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEAMS_SR_odw_stgdbQ;
        
        /// <summary>
        /// Label2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label2;
        
        /// <summary>
        /// lblEAMS_SR_odw_gisSR control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEAMS_SR_odw_gisSR;
        
        /// <summary>
        /// lblEAMS_SR_odw_gisSRQR control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEAMS_SR_odw_gisSRQR;
        
        /// <summary>
        /// lblEAMS_SR_odw_gisSRQ control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEAMS_SR_odw_gisSRQ;
        
        /// <summary>
        /// reflblEAMS_SR_odw_tbl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label reflblEAMS_SR_odw_tbl;
        
        /// <summary>
        /// lblEAMS_SR_odw_tbl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEAMS_SR_odw_tbl;
        
        /// <summary>
        /// lblEAMS_SR_odw_tblQR control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEAMS_SR_odw_tblQR;
        
        /// <summary>
        /// lblEAMS_SR_odw_tblQ control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEAMS_SR_odw_tblQ;
        
        /// <summary>
        /// reflblEAMS_SR_odw_vw control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label reflblEAMS_SR_odw_vw;
        
        /// <summary>
        /// lblEAMS_SR_odw_vw control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEAMS_SR_odw_vw;
        
        /// <summary>
        /// lblEAMS_SR_odw_vwQR control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEAMS_SR_odw_vwQR;
        
        /// <summary>
        /// lblEAMS_SR_odw_vwQ control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEAMS_SR_odw_vwQ;
        
        /// <summary>
        /// reflblEAMS_SR_gis_srvce control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label reflblEAMS_SR_gis_srvce;
        
        /// <summary>
        /// lblEAMS_SR_gis_srvce control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEAMS_SR_gis_srvce;
        
        /// <summary>
        /// lblEAMS_SR_gis_srvceQR control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEAMS_SR_gis_srvceQR;
        
        /// <summary>
        /// lblEAMS_SR_gis_srvceQ control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEAMS_SR_gis_srvceQ;
        
        /// <summary>
        /// lblEAMS_wo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEAMS_wo;
        
        /// <summary>
        /// reflblEAMS_wo_isd_actdb control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label reflblEAMS_wo_isd_actdb;
        
        /// <summary>
        /// lblEAMS_wo_isd_actdb control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEAMS_wo_isd_actdb;
        
        /// <summary>
        /// lblEAMS_wo_isd_actdbQR control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEAMS_wo_isd_actdbQR;
        
        /// <summary>
        /// lblEAMS_wo_isd_actdbQ control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEAMS_wo_isd_actdbQ;
        
        /// <summary>
        /// reflblEAMS_wo_isd_stgdb control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label reflblEAMS_wo_isd_stgdb;
        
        /// <summary>
        /// lblEAMS_wo_isd_stgdb control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEAMS_wo_isd_stgdb;
        
        /// <summary>
        /// lblEAMS_wo_isd_stgdbQR control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEAMS_wo_isd_stgdbQR;
        
        /// <summary>
        /// lblEAMS_wo_isd_stgdbQ control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEAMS_wo_isd_stgdbQ;
        
        /// <summary>
        /// reflblEAMS_wo_isd_stgdbFC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label reflblEAMS_wo_isd_stgdbFC;
        
        /// <summary>
        /// lblEAMS_wo_isd_stgdbFC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEAMS_wo_isd_stgdbFC;
        
        /// <summary>
        /// lblEAMS_wo_isd_stgdbFCQR control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEAMS_wo_isd_stgdbFCQR;
        
        /// <summary>
        /// lblEAMS_wo_isd_stgdbFCQ control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEAMS_wo_isd_stgdbFCQ;
        
        /// <summary>
        /// reflblEAMS_wo_odw_stg control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label reflblEAMS_wo_odw_stg;
        
        /// <summary>
        /// lblEAMS_wo_odw_stg control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEAMS_wo_odw_stg;
        
        /// <summary>
        /// lblEAMS_wo_odw_stgQR control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEAMS_wo_odw_stgQR;
        
        /// <summary>
        /// lblEAMS_wo_odw_stgQ control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEAMS_wo_odw_stgQ;
        
        /// <summary>
        /// Label4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label4;
        
        /// <summary>
        /// lbl_odw_giswotbl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbl_odw_giswotbl;
        
        /// <summary>
        /// lbl_odw_giswotblQR control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbl_odw_giswotblQR;
        
        /// <summary>
        /// lbl_odw_giswotblQ control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbl_odw_giswotblQ;
        
        /// <summary>
        /// reflblEAMS_wo_odw_tbl_gis control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label reflblEAMS_wo_odw_tbl_gis;
        
        /// <summary>
        /// lblEAMS_wo_odw_tbl_gis control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEAMS_wo_odw_tbl_gis;
        
        /// <summary>
        /// lblEAMS_wo_odw_tbl_gisQR control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEAMS_wo_odw_tbl_gisQR;
        
        /// <summary>
        /// lblEAMS_wo_odw_tbl_gisQ control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEAMS_wo_odw_tbl_gisQ;
        
        /// <summary>
        /// reflblEAMS_wo_odw_vw control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label reflblEAMS_wo_odw_vw;
        
        /// <summary>
        /// lblEAMS_wo_odw_vw control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEAMS_wo_odw_vw;
        
        /// <summary>
        /// lblEAMS_wo_odw_vwQR control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEAMS_wo_odw_vwQR;
        
        /// <summary>
        /// lblEAMS_wo_odw_vwQ control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEAMS_wo_odw_vwQ;
        
        /// <summary>
        /// ref_lblEAMS_wo_odw_own_vw control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ref_lblEAMS_wo_odw_own_vw;
        
        /// <summary>
        /// lblEAMS_wo_odw_own_vw control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEAMS_wo_odw_own_vw;
        
        /// <summary>
        /// lblEAMS_wo_odw_own_vwQR control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEAMS_wo_odw_own_vwQR;
        
        /// <summary>
        /// lblEAMS_wo_odw_own_vwQ control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEAMS_wo_odw_own_vwQ;
        
        /// <summary>
        /// reflblEAMS_wo_gis_srvce control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label reflblEAMS_wo_gis_srvce;
        
        /// <summary>
        /// lblEAMS_wo_gis_srvce control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEAMS_wo_gis_srvce;
        
        /// <summary>
        /// lblEAMS_wo_gis_srvceQR control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEAMS_wo_gis_srvceQR;
        
        /// <summary>
        /// lblEAMS_wo_gis_srvceQ control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEAMS_wo_gis_srvceQ;
        
        /// <summary>
        /// reflblEAMS_wo_gis_srvce_vw control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label reflblEAMS_wo_gis_srvce_vw;
        
        /// <summary>
        /// lblEAMS_wo_gis_srvce_vw control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEAMS_wo_gis_srvce_vw;
        
        /// <summary>
        /// lblEAMS_wo_gis_srvce_vwQR control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEAMS_wo_gis_srvce_vwQR;
        
        /// <summary>
        /// lblEAMS_wo_gis_srvce_vwQ control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEAMS_wo_gis_srvce_vwQ;
        
        /// <summary>
        /// ref_lblwoall control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ref_lblwoall;
        
        /// <summary>
        /// lblwoall control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblwoall;
        
        /// <summary>
        /// lblwoallQR control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblwoallQR;
        
        /// <summary>
        /// lblwoallQ control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblwoallQ;
    }
}
