USE [ODW]
GO

/****** Object:  StoredProcedure [EAMS].[USP_GET_CLASS_SPECIFICATION]    Script Date: 9/14/2022 2:45:53 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		<Rana Fahad>
-- Create date: <06-07-2021>
-- Description:	<Get values from class specfication table>
-- =============================================
CREATE OR ALTER    PROCEDURE [EAMS].[USP_GET_CLASS_SPECIFICATION]
@ASSETATTRID varchar(500) = ''
/*
exec [EAMS].[USP_GET_CLASS_SPECIFICATION] 'THRDP,PROPERTY_TYPE'
*/
AS
BEGIN

Create Table #temp(ALNValue NVARCHAR(50),  CLASSSPECID INT, ClassStructureId NVARCHAR(50),SEQ INT ,  ASSETATTRID varchar(50),ASSETATTRIDODW varchar(50))

INSERT INTO #temp (ALNValue,CLASSSPECID,ClassStructureId,SEQ,ASSETATTRID,ASSETATTRIDODW) VALUES(   '' ,129479,'5144',1,'AVG_FLOOD_DEPTH','AVG_FLOOD_DEPTH')
INSERT INTO #temp (ALNValue,CLASSSPECID,ClassStructureId,SEQ,ASSETATTRID,ASSETATTRIDODW) VALUES(   '' ,129487,'5144',2,'DUPLICATE','DUPLICATE')
INSERT INTO #temp (ALNValue,CLASSSPECID,ClassStructureId,SEQ,ASSETATTRID,ASSETATTRIDODW) VALUES(   '' ,129522,'5144',3,'EVENT','EVENT')
INSERT INTO #temp (ALNValue,CLASSSPECID,ClassStructureId,SEQ,ASSETATTRID,ASSETATTRIDODW) VALUES(   '' ,129482,'5144',4,'EXPT_RESOL_TIME','EXPT_RESOL_TIME')

INSERT INTO #temp (ALNValue,CLASSSPECID,ClassStructureId,SEQ,ASSETATTRID,ASSETATTRIDODW) VALUES(   '' ,129488,'5144',5,'FLODLOC','FLODLOC')
INSERT INTO #temp (ALNValue,CLASSSPECID,ClassStructureId,SEQ,ASSETATTRID,ASSETATTRIDODW) VALUES(   '' ,129485,'5144',6,'FLOOD_EXTNT','FLOOD_EXTNT')
INSERT INTO #temp (ALNValue,CLASSSPECID,ClassStructureId,SEQ,ASSETATTRID,ASSETATTRIDODW) VALUES(   '' ,129486,'5144',7,'HOTSPOT NUMBER','HOTSPOT NUMBER')
INSERT INTO #temp (ALNValue,CLASSSPECID,ClassStructureId,SEQ,ASSETATTRID,ASSETATTRIDODW) VALUES(   '' ,129489,'5144',8,'LOSS_ROAD_AVL','LOSS_ROAD_AVL')

INSERT INTO #temp (ALNValue,CLASSSPECID,ClassStructureId,SEQ,ASSETATTRID,ASSETATTRIDODW) VALUES(   '' ,129490,'5144',9,'NO_OF_LANE','NO_OF_LANE')
INSERT INTO #temp (ALNValue,CLASSSPECID,ClassStructureId,SEQ,ASSETATTRID,ASSETATTRIDODW) VALUES(   '' ,129491,'5144',10,'NO_OF_LANE_BLOCK','NO_OF_LANE_BLOCK')
INSERT INTO #temp (ALNValue,CLASSSPECID,ClassStructureId,SEQ,ASSETATTRID,ASSETATTRIDODW) VALUES(   '' ,129492,'5144',11,'NO_TANKER_TRIP','NO_TANKER_TRIP')
INSERT INTO #temp (ALNValue,CLASSSPECID,ClassStructureId,SEQ,ASSETATTRID,ASSETATTRIDODW) VALUES(   '' ,129498,'5144',12,'PARENT_CRMS_SR_NO','PARENT_CRMS_SR_NO')

INSERT INTO #temp (ALNValue,CLASSSPECID,ClassStructureId,SEQ,ASSETATTRID,ASSETATTRIDODW) VALUES(   '' ,129499,'5144',13,'PROJECT ID','PROJECT ID')
INSERT INTO #temp (ALNValue,CLASSSPECID,ClassStructureId,SEQ,ASSETATTRID,ASSETATTRIDODW) VALUES(   '' ,129493,'5144',14,'PROPERTY_DMG','PROPERTY_DMG')
INSERT INTO #temp (ALNValue,CLASSSPECID,ClassStructureId,SEQ,ASSETATTRID,ASSETATTRIDODW) VALUES(   '' ,129500,'5144',15,'PUMP_RUN_HRS','PUMP_RUN_HRS')
INSERT INTO #temp (ALNValue,CLASSSPECID,ClassStructureId,SEQ,ASSETATTRID,ASSETATTRIDODW) VALUES(   '' ,129501,'5144',16,'PUMP_USED','PUMP_USED')

INSERT INTO #temp (ALNValue,CLASSSPECID,ClassStructureId,SEQ,ASSETATTRID,ASSETATTRIDODW) VALUES(   'DRAINAGE' ,129509,'5144',17,'RELATED_TO','RELATED_TO')
INSERT INTO #temp (ALNValue,CLASSSPECID,ClassStructureId,SEQ,ASSETATTRID,ASSETATTRIDODW) VALUES(   '' ,129523,'5144',18,'RESTRICTEDAREA','RESTRICTEDAREA')
INSERT INTO #temp (ALNValue,CLASSSPECID,ClassStructureId,SEQ,ASSETATTRID,ASSETATTRIDODW) VALUES(   '' ,129502,'5144',19,'ROOD_CLASS','ROOD_CLASS')
INSERT INTO #temp (ALNValue,CLASSSPECID,ClassStructureId,SEQ,ASSETATTRID,ASSETATTRIDODW) VALUES(   '' ,129503,'5144',20,'SGW_NETWRK_AVL','SGW_NETWRK_AVL')

INSERT INTO #temp (ALNValue,CLASSSPECID,ClassStructureId,SEQ,ASSETATTRID,ASSETATTRIDODW) VALUES(   '' ,129504,'5144',21,'SGW_NETWRK_TYPE','SGW_NETWRK_TYPE')
INSERT INTO #temp (ALNValue,CLASSSPECID,ClassStructureId,SEQ,ASSETATTRID,ASSETATTRIDODW) VALUES(   '' ,129505,'5144',22,'THRDP','THRDP')

SELECT * FROM #temp
DROP TABLE #temp
END

GO


